name: E2E Screenshot Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: demo/package-lock.json
    
    - name: Install dependencies
      working-directory: ./demo
      run: npm ci
    
    - name: Install Playwright Browsers
      working-directory: ./demo
      run: npx playwright install --with-deps chromium
    
    - name: Run Playwright tests
      working-directory: ./demo
      run: npm run test:e2e
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: demo/playwright-report/
        retention-days: 30
    
    - name: Upload screenshots on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results
        path: demo/test-results/
        retention-days: 30

